### ISSUE TITLE
Enabling bitcode

### ISSUE THREAD

**Issue by roldy** [open-pay/openpay-ios#1]
Am placing in a request to enable bitcode with the library. 
An update is overdue. 
Thank you.

**Comment by srdzdv** [comment]
Getting the same Error here:

"You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target."

Any update on this?

Thanks.

**Comment by edgarjs** [comment]
Yes please! This is the only library in my project that does not support bitcode yet.

**Comment by AlexisLeon** [comment]
+1

Error details:
```bash
ld: '.../openpay.a(Openpay.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '.../openpay.a' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by richard182** [comment]
+2

Error details:

ld: '.../openpay.a(Openpay.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '.../openpay.a' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by bengus** [comment]
Extra Bitcode settings

Well, turns out one setting wasn't enough. Xcode will only build a project with Bitcode support if you Archive it, which is not usually the case when you're working with libraries. To get around that, you can use either one of two settings on your project (whichever one you prefer):

On Build Settings -> Other C flags, set Debug to -fembed-bitcode-marker, and Release to -fembed-bitcode. Make sure that is set for your project, and not the targets. (thanks @naishta for pointing that out!)

https://medium.com/@heitorburger/static-libraries-frameworks-and-bitcode-6d8f784478a9
